openapi: 3.0.0
info:
  description: An OpenAPI for EVE Online
  title: EVE Swagger Interface Alliance Calendar API
  version: '1.36'
servers:
- url: https://esi.evetech.net/latest
tags:
- name: Calendar
paths:
  /characters/{character_id}/calendar/:
    get:
      description: 'Get 50 event summaries from the calendar. If no from_event ID is given, the resource will return the next 50 chronological event summaries from now. If a from_event ID is specified, it will return the next 50 chronological event summaries from after that event


        ---

        Alternate route: `/dev/characters/{character_id}/calendar/`


        Alternate route: `/legacy/characters/{character_id}/calendar/`


        Alternate route: `/v1/characters/{character_id}/calendar/`


        Alternate route: `/v2/characters/{character_id}/calendar/`


        ---

        This route is cached for up to 5 seconds'
      operationId: get_characters_character_id_calendar
      parameters:
      - $ref: '#/components/parameters/character_id'
      - $ref: '#/components/parameters/datasource'
      - description: The event ID to retrieve events from
        in: query
        name: from_event
        required: false
        schema:
          type: integer
          format: int32
        example: 1
      - $ref: '#/components/parameters/If-None-Match'
      - $ref: '#/components/parameters/token'
      responses:
        '200':
          description: A collection of event summaries
          headers:
            Cache-Control:
              description: The caching mechanism used
              schema:
                type: string
            ETag:
              description: RFC7232 compliant entity tag
              schema:
                type: string
            Expires:
              description: RFC7231 formatted datetime string
              schema:
                type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              schema:
                type: string
          content:
            application/json:
              schema:
                description: Up to 50 events from now or the event you requested
                items:
                  description: event
                  properties:
                    event_date:
                      description: event_date string
                      format: date-time
                      title: get_characters_character_id_calendar_event_date
                      type: string
                    event_id:
                      description: event_id integer
                      format: int32
                      title: get_characters_character_id_calendar_event_id
                      type: integer
                    event_response:
                      description: event_response string
                      enum:
                      - declined
                      - not_responded
                      - accepted
                      - tentative
                      title: get_characters_character_id_calendar_event_response
                      type: string
                    importance:
                      description: importance integer
                      format: int32
                      title: get_characters_character_id_calendar_importance
                      type: integer
                    title:
                      description: title string
                      title: get_characters_character_id_calendar_title
                      type: string
                  title: get_characters_character_id_calendar_200_ok
                  type: object
                maxItems: 50
                title: get_characters_character_id_calendar_ok
                type: array
              examples:
                response:
                  value:
                  - event_date: 2016-06-26 20:00:00+00:00
                    event_id: 1386435
                    event_response: accepted
                    importance: 0
                    title: o7 The EVE Online Show
        '304':
          description: Not modified
          headers:
            Cache-Control:
              description: The caching mechanism used
              schema:
                type: string
            ETag:
              description: RFC7232 compliant entity tag
              schema:
                type: string
            Expires:
              description: RFC7231 formatted datetime string
              schema:
                type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              schema:
                type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request'
              examples:
                response:
                  value:
                    error: Bad request message
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
              examples:
                response:
                  value:
                    error: Unauthorized message
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
              examples:
                response:
                  value:
                    error: Forbidden message
        '420':
          description: Error limited
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_limited'
              examples:
                response:
                  value:
                    error: Error limited message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
              examples:
                response:
                  value:
                    error: Internal server error message
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_unavailable'
              examples:
                response:
                  value:
                    error: Service unavailable message
        '504':
          description: Gateway timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway_timeout'
              examples:
                response:
                  value:
                    error: Gateway timeout message
      security:
      - evesso:
        - esi-calendar.read_calendar_events.v1
      summary: EVE Online List Calendar Event Summaries
      tags:
      - Calendar
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-cached-seconds: 5
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /characters/{character_id}/calendar/{event_id}/:
    get:
      description: 'Get all the information for a specific event


        ---

        Alternate route: `/dev/characters/{character_id}/calendar/{event_id}/`


        Alternate route: `/legacy/characters/{character_id}/calendar/{event_id}/`


        Alternate route: `/v3/characters/{character_id}/calendar/{event_id}/`


        Alternate route: `/v4/characters/{character_id}/calendar/{event_id}/`


        ---

        This route is cached for up to 5 seconds'
      operationId: get_characters_character_id_calendar_event_id
      parameters:
      - $ref: '#/components/parameters/character_id'
      - $ref: '#/components/parameters/datasource'
      - description: The id of the event requested
        in: path
        name: event_id
        required: true
        schema:
          type: integer
          format: int32
        example: 1001
      - $ref: '#/components/parameters/If-None-Match'
      - $ref: '#/components/parameters/token'
      responses:
        '200':
          description: Full details of a specific event
          headers:
            Cache-Control:
              description: The caching mechanism used
              schema:
                type: string
            ETag:
              description: RFC7232 compliant entity tag
              schema:
                type: string
            Expires:
              description: RFC7231 formatted datetime string
              schema:
                type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              schema:
                type: string
          content:
            application/json:
              schema:
                description: Full details of a specific event
                properties:
                  date:
                    description: date string
                    format: date-time
                    title: get_characters_character_id_calendar_event_id_date
                    type: string
                  duration:
                    description: Length in minutes
                    format: int32
                    title: get_characters_character_id_calendar_event_id_duration
                    type: integer
                  event_id:
                    description: event_id integer
                    format: int32
                    title: get_characters_character_id_calendar_event_id_event_id
                    type: integer
                  importance:
                    description: importance integer
                    format: int32
                    title: get_characters_character_id_calendar_event_id_importance
                    type: integer
                  owner_id:
                    description: owner_id integer
                    format: int32
                    title: get_characters_character_id_calendar_event_id_owner_id
                    type: integer
                  owner_name:
                    description: owner_name string
                    title: get_characters_character_id_calendar_event_id_owner_name
                    type: string
                  owner_type:
                    description: owner_type string
                    enum:
                    - eve_server
                    - corporation
                    - faction
                    - character
                    - alliance
                    title: get_characters_character_id_calendar_event_id_owner_type
                    type: string
                  response:
                    description: response string
                    title: get_characters_character_id_calendar_event_id_response
                    type: string
                  text:
                    description: text string
                    title: get_characters_character_id_calendar_event_id_text
                    type: string
                  title:
                    description: title string
                    title: get_characters_character_id_calendar_event_id_title
                    type: string
                required:
                - event_id
                - owner_id
                - owner_name
                - date
                - title
                - duration
                - importance
                - response
                - text
                - owner_type
                title: get_characters_character_id_calendar_event_id_ok
                type: object
              examples:
                response:
                  value:
                    date: 2016-06-26 21:00:00+00:00
                    duration: 60
                    event_id: 1386435
                    importance: 1
                    owner_id: 1
                    owner_name: EVE System
                    owner_type: eve_server
                    response: Undecided
                    text: 'o7: The EVE Online Show features latest developer news, fast paced action, community overviews and a lot more with CCP Guard and CCP Mimic. Join the thrilling o7 live broadcast at 20:00 EVE time (=UTC) on <a href="http://www.twitch.tv/ccp">EVE TV</a>. Don''t miss it!'
                    title: o7 The EVE Online Show
        '304':
          description: Not modified
          headers:
            Cache-Control:
              description: The caching mechanism used
              schema:
                type: string
            ETag:
              description: RFC7232 compliant entity tag
              schema:
                type: string
            Expires:
              description: RFC7231 formatted datetime string
              schema:
                type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              schema:
                type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request'
              examples:
                response:
                  value:
                    error: Bad request message
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
              examples:
                response:
                  value:
                    error: Unauthorized message
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
              examples:
                response:
                  value:
                    error: Forbidden message
        '404':
          description: Not found
          content:
            application/json:
              schema:
                description: Not found
                properties:
                  error:
                    description: Not found message
                    title: get_characters_character_id_calendar_event_id_404_not_found
                    type: string
                title: get_characters_character_id_calendar_event_id_not_found
                type: object
              examples:
                response:
                  value:
                    error: Not found message
        '420':
          description: Error limited
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_limited'
              examples:
                response:
                  value:
                    error: Error limited message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
              examples:
                response:
                  value:
                    error: Internal server error message
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_unavailable'
              examples:
                response:
                  value:
                    error: Service unavailable message
        '504':
          description: Gateway timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway_timeout'
              examples:
                response:
                  value:
                    error: Gateway timeout message
      security:
      - evesso:
        - esi-calendar.read_calendar_events.v1
      summary: EVE Online Get an Event
      tags:
      - Calendar
      x-alternate-versions:
      - dev
      - legacy
      - v3
      - v4
      x-cached-seconds: 5
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    put:
      description: 'Set your response status to an event


        ---

        Alternate route: `/dev/characters/{character_id}/calendar/{event_id}/`


        Alternate route: `/legacy/characters/{character_id}/calendar/{event_id}/`


        Alternate route: `/v3/characters/{character_id}/calendar/{event_id}/`


        Alternate route: `/v4/characters/{character_id}/calendar/{event_id}/`


        ---

        This route is cached for up to 5 seconds'
      operationId: put_characters_character_id_calendar_event_id
      parameters:
      - $ref: '#/components/parameters/character_id'
      - $ref: '#/components/parameters/datasource'
      - description: The ID of the event requested
        in: path
        name: event_id
        required: true
        schema:
          type: integer
          format: int32
        example: 1001
      - $ref: '#/components/parameters/token'
      requestBody:
        content:
          application/json:
            schema:
              description: response object
              properties:
                response:
                  description: response string
                  enum:
                  - accepted
                  - declined
                  - tentative
                  title: put_characters_character_id_calendar_event_id_response_response
                  type: string
              required:
              - response
              title: put_characters_character_id_calendar_event_id_response
              type: object
            examples:
              PutCharactersCharacterIdCalendarEventIdRequestExample:
                summary: Default put_characters_character_id_calendar_event_id request
                x-microcks-default: true
                value:
                  response: accepted
        description: The response value to set, overriding current value
        required: true
      responses:
        '204':
          description: Event updated
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request'
              examples:
                response:
                  value:
                    error: Bad request message
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
              examples:
                response:
                  value:
                    error: Unauthorized message
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
              examples:
                response:
                  value:
                    error: Forbidden message
        '420':
          description: Error limited
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_limited'
              examples:
                response:
                  value:
                    error: Error limited message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
              examples:
                response:
                  value:
                    error: Internal server error message
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_unavailable'
              examples:
                response:
                  value:
                    error: Service unavailable message
        '504':
          description: Gateway timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway_timeout'
              examples:
                response:
                  value:
                    error: Gateway timeout message
      security:
      - evesso:
        - esi-calendar.respond_calendar_events.v1
      summary: EVE Online Respond to an Event
      tags:
      - Calendar
      x-alternate-versions:
      - dev
      - legacy
      - v3
      - v4
      x-cached-seconds: 5
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /characters/{character_id}/calendar/{event_id}/attendees/:
    get:
      description: 'Get all invited attendees for a given event


        ---

        Alternate route: `/dev/characters/{character_id}/calendar/{event_id}/attendees/`


        Alternate route: `/legacy/characters/{character_id}/calendar/{event_id}/attendees/`


        Alternate route: `/v1/characters/{character_id}/calendar/{event_id}/attendees/`


        Alternate route: `/v2/characters/{character_id}/calendar/{event_id}/attendees/`


        ---

        This route is cached for up to 600 seconds'
      operationId: get_characters_character_id_calendar_event_id_attendees
      parameters:
      - $ref: '#/components/parameters/character_id'
      - $ref: '#/components/parameters/datasource'
      - description: The id of the event requested
        in: path
        name: event_id
        required: true
        schema:
          type: integer
          format: int32
        example: 1001
      - $ref: '#/components/parameters/If-None-Match'
      - $ref: '#/components/parameters/token'
      responses:
        '200':
          description: List of attendees
          headers:
            Cache-Control:
              description: The caching mechanism used
              schema:
                type: string
            ETag:
              description: RFC7232 compliant entity tag
              schema:
                type: string
            Expires:
              description: RFC7231 formatted datetime string
              schema:
                type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              schema:
                type: string
          content:
            application/json:
              schema:
                description: List of attendees for a given event
                items:
                  description: character_id and response of an attendee
                  properties:
                    character_id:
                      description: character_id integer
                      format: int32
                      title: get_characters_character_id_calendar_event_id_attendees_character_id
                      type: integer
                    event_response:
                      description: event_response string
                      enum:
                      - declined
                      - not_responded
                      - accepted
                      - tentative
                      title: get_characters_character_id_calendar_event_id_attendees_event_response
                      type: string
                  title: get_characters_character_id_calendar_event_id_attendees_200_ok
                  type: object
                maxItems: 100
                title: get_characters_character_id_calendar_event_id_attendees_ok
                type: array
              examples:
                response:
                  value:
                  - character_id: 2112625428
                    event_response: accepted
                  - character_id: 95465499
                    event_response: tentative
        '304':
          description: Not modified
          headers:
            Cache-Control:
              description: The caching mechanism used
              schema:
                type: string
            ETag:
              description: RFC7232 compliant entity tag
              schema:
                type: string
            Expires:
              description: RFC7231 formatted datetime string
              schema:
                type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              schema:
                type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request'
              examples:
                response:
                  value:
                    error: Bad request message
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
              examples:
                response:
                  value:
                    error: Unauthorized message
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
              examples:
                response:
                  value:
                    error: Forbidden message
        '404':
          description: Not found
          content:
            application/json:
              schema:
                description: Not found
                properties:
                  error:
                    description: Not found message
                    title: get_characters_character_id_calendar_event_id_attendees_404_not_found
                    type: string
                title: get_characters_character_id_calendar_event_id_attendees_not_found
                type: object
              examples:
                response:
                  value:
                    error: Not found message
        '420':
          description: Error limited
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_limited'
              examples:
                response:
                  value:
                    error: Error limited message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
              examples:
                response:
                  value:
                    error: Internal server error message
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_unavailable'
              examples:
                response:
                  value:
                    error: Service unavailable message
        '504':
          description: Gateway timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway_timeout'
              examples:
                response:
                  value:
                    error: Gateway timeout message
      security:
      - evesso:
        - esi-calendar.read_calendar_events.v1
      summary: EVE Online Get Attendees
      tags:
      - Calendar
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-cached-seconds: 600
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /v1/characters/{character_id}/calendar/:
    get:
      description: 'Get 50 event summaries from the calendar. If no from_event ID is given, the resource will return the next 50 chronological event summaries from now. If a from_event ID is specified, it will return the next 50 chronological event summaries from after that event


        ---


        This route is cached for up to 5 seconds'
      operationId: get_characters_character_id_calendar
      parameters:
      - $ref: '#/parameters/character_id'
      - $ref: '#/parameters/datasource'
      - description: The event ID to retrieve events from
        format: int32
        in: query
        name: from_event
        required: false
        type: integer
      - $ref: '#/parameters/If-None-Match'
      - $ref: '#/parameters/token'
      responses:
        '200':
          description: A collection of event summaries
          examples:
            application/json:
            - event_date: '2016-06-26T20:00:00Z'
              event_id: 1386435
              event_response: accepted
              importance: 0
              title: o7 The EVE Online Show
          headers:
            Cache-Control:
              description: The caching mechanism used
              type: string
            ETag:
              description: RFC7232 compliant entity tag
              type: string
            Expires:
              description: RFC7231 formatted datetime string
              type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              type: string
          schema:
            description: Up to 50 events from now or the event you requested
            items:
              description: event
              properties:
                event_date:
                  description: event_date string
                  format: date-time
                  title: get_characters_character_id_calendar_event_date
                  type: string
                event_id:
                  description: event_id integer
                  format: int32
                  title: get_characters_character_id_calendar_event_id
                  type: integer
                event_response:
                  description: event_response string
                  enum:
                  - declined
                  - not_responded
                  - accepted
                  - tentative
                  title: get_characters_character_id_calendar_event_response
                  type: string
                importance:
                  description: importance integer
                  format: int32
                  title: get_characters_character_id_calendar_importance
                  type: integer
                title:
                  description: title string
                  title: get_characters_character_id_calendar_title
                  type: string
              title: get_characters_character_id_calendar_200_ok
              type: object
            maxItems: 50
            title: get_characters_character_id_calendar_ok
            type: array
        '304':
          description: Not modified
          headers:
            Cache-Control:
              description: The caching mechanism used
              type: string
            ETag:
              description: RFC7232 compliant entity tag
              type: string
            Expires:
              description: RFC7231 formatted datetime string
              type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              type: string
        '400':
          description: Bad request
          examples:
            application/json:
              error: Bad request message
          schema:
            $ref: '#/definitions/bad_request'
        '401':
          description: Unauthorized
          examples:
            application/json:
              error: Unauthorized message
          schema:
            $ref: '#/definitions/unauthorized'
        '403':
          description: Forbidden
          examples:
            application/json:
              error: Forbidden message
          schema:
            $ref: '#/definitions/forbidden'
        '420':
          description: Error limited
          examples:
            application/json:
              error: Error limited message
          schema:
            $ref: '#/definitions/error_limited'
        '500':
          description: Internal server error
          examples:
            application/json:
              error: Internal server error message
          schema:
            $ref: '#/definitions/internal_server_error'
        '503':
          description: Service unavailable
          examples:
            application/json:
              error: Service unavailable message
          schema:
            $ref: '#/definitions/service_unavailable'
        '504':
          description: Gateway timeout
          examples:
            application/json:
              error: Gateway timeout message
          schema:
            $ref: '#/definitions/gateway_timeout'
      security:
      - evesso:
        - esi-calendar.read_calendar_events.v1
      summary: List calendar event summaries
      tags:
      - Calendar
      x-alternate-versions:
      - latest
      - legacy
      - v1
      - v2
      x-cached-seconds: 5
  /v1/characters/{character_id}/calendar/{event_id}/attendees/:
    get:
      description: 'Get all invited attendees for a given event


        ---


        This route is cached for up to 600 seconds'
      operationId: get_characters_character_id_calendar_event_id_attendees
      parameters:
      - $ref: '#/parameters/character_id'
      - $ref: '#/parameters/datasource'
      - description: The id of the event requested
        format: int32
        in: path
        name: event_id
        required: true
        type: integer
      - $ref: '#/parameters/If-None-Match'
      - $ref: '#/parameters/token'
      responses:
        '200':
          description: List of attendees
          examples:
            application/json:
            - character_id: 2112625428
              event_response: accepted
            - character_id: 95465499
              event_response: tentative
          headers:
            Cache-Control:
              description: The caching mechanism used
              type: string
            ETag:
              description: RFC7232 compliant entity tag
              type: string
            Expires:
              description: RFC7231 formatted datetime string
              type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              type: string
          schema:
            description: List of attendees for a given event
            items:
              description: character_id and response of an attendee
              properties:
                character_id:
                  description: character_id integer
                  format: int32
                  title: get_characters_character_id_calendar_event_id_attendees_character_id
                  type: integer
                event_response:
                  description: event_response string
                  enum:
                  - declined
                  - not_responded
                  - accepted
                  - tentative
                  title: get_characters_character_id_calendar_event_id_attendees_event_response
                  type: string
              title: get_characters_character_id_calendar_event_id_attendees_200_ok
              type: object
            maxItems: 100
            title: get_characters_character_id_calendar_event_id_attendees_ok
            type: array
        '304':
          description: Not modified
          headers:
            Cache-Control:
              description: The caching mechanism used
              type: string
            ETag:
              description: RFC7232 compliant entity tag
              type: string
            Expires:
              description: RFC7231 formatted datetime string
              type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              type: string
        '400':
          description: Bad request
          examples:
            application/json:
              error: Bad request message
          schema:
            $ref: '#/definitions/bad_request'
        '401':
          description: Unauthorized
          examples:
            application/json:
              error: Unauthorized message
          schema:
            $ref: '#/definitions/unauthorized'
        '403':
          description: Forbidden
          examples:
            application/json:
              error: Forbidden message
          schema:
            $ref: '#/definitions/forbidden'
        '404':
          description: Not found
          examples:
            application/json:
              error: Not found message
          schema:
            description: Not found
            properties:
              error:
                description: Not found message
                title: get_characters_character_id_calendar_event_id_attendees_404_not_found
                type: string
            title: get_characters_character_id_calendar_event_id_attendees_not_found
            type: object
        '420':
          description: Error limited
          examples:
            application/json:
              error: Error limited message
          schema:
            $ref: '#/definitions/error_limited'
        '500':
          description: Internal server error
          examples:
            application/json:
              error: Internal server error message
          schema:
            $ref: '#/definitions/internal_server_error'
        '503':
          description: Service unavailable
          examples:
            application/json:
              error: Service unavailable message
          schema:
            $ref: '#/definitions/service_unavailable'
        '504':
          description: Gateway timeout
          examples:
            application/json:
              error: Gateway timeout message
          schema:
            $ref: '#/definitions/gateway_timeout'
      security:
      - evesso:
        - esi-calendar.read_calendar_events.v1
      summary: Get attendees
      tags:
      - Calendar
      x-alternate-versions:
      - latest
      - legacy
      - v1
      - v2
      x-cached-seconds: 600
  /v3/characters/{character_id}/calendar/{event_id}/:
    get:
      description: 'Get all the information for a specific event


        ---


        This route is cached for up to 5 seconds'
      operationId: get_characters_character_id_calendar_event_id
      parameters:
      - $ref: '#/parameters/character_id'
      - $ref: '#/parameters/datasource'
      - description: The id of the event requested
        format: int32
        in: path
        name: event_id
        required: true
        type: integer
      - $ref: '#/parameters/If-None-Match'
      - $ref: '#/parameters/token'
      responses:
        '200':
          description: Full details of a specific event
          examples:
            application/json:
              date: '2016-06-26T21:00:00Z'
              duration: 60
              event_id: 1386435
              importance: 1
              owner_id: 1
              owner_name: EVE System
              owner_type: eve_server
              response: Undecided
              text: 'o7: The EVE Online Show features latest developer news, fast paced action, community overviews and a lot more with CCP Guard and CCP Mimic. Join the thrilling o7 live broadcast at 20:00 EVE time (=UTC) on <a href="http://www.twitch.tv/ccp">EVE TV</a>. Don''t miss it!'
              title: o7 The EVE Online Show
          headers:
            Cache-Control:
              description: The caching mechanism used
              type: string
            ETag:
              description: RFC7232 compliant entity tag
              type: string
            Expires:
              description: RFC7231 formatted datetime string
              type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              type: string
          schema:
            description: Full details of a specific event
            properties:
              date:
                description: date string
                format: date-time
                title: get_characters_character_id_calendar_event_id_date
                type: string
              duration:
                description: Length in minutes
                format: int32
                title: get_characters_character_id_calendar_event_id_duration
                type: integer
              event_id:
                description: event_id integer
                format: int32
                title: get_characters_character_id_calendar_event_id_event_id
                type: integer
              importance:
                description: importance integer
                format: int32
                title: get_characters_character_id_calendar_event_id_importance
                type: integer
              owner_id:
                description: owner_id integer
                format: int32
                title: get_characters_character_id_calendar_event_id_owner_id
                type: integer
              owner_name:
                description: owner_name string
                title: get_characters_character_id_calendar_event_id_owner_name
                type: string
              owner_type:
                description: owner_type string
                enum:
                - eve_server
                - corporation
                - faction
                - character
                - alliance
                title: get_characters_character_id_calendar_event_id_owner_type
                type: string
              response:
                description: response string
                title: get_characters_character_id_calendar_event_id_response
                type: string
              text:
                description: text string
                title: get_characters_character_id_calendar_event_id_text
                type: string
              title:
                description: title string
                title: get_characters_character_id_calendar_event_id_title
                type: string
            required:
            - event_id
            - owner_id
            - owner_name
            - date
            - title
            - duration
            - importance
            - response
            - text
            - owner_type
            title: get_characters_character_id_calendar_event_id_ok
            type: object
        '304':
          description: Not modified
          headers:
            Cache-Control:
              description: The caching mechanism used
              type: string
            ETag:
              description: RFC7232 compliant entity tag
              type: string
            Expires:
              description: RFC7231 formatted datetime string
              type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              type: string
        '400':
          description: Bad request
          examples:
            application/json:
              error: Bad request message
          schema:
            $ref: '#/definitions/bad_request'
        '401':
          description: Unauthorized
          examples:
            application/json:
              error: Unauthorized message
          schema:
            $ref: '#/definitions/unauthorized'
        '403':
          description: Forbidden
          examples:
            application/json:
              error: Forbidden message
          schema:
            $ref: '#/definitions/forbidden'
        '404':
          description: Not found
          examples:
            application/json:
              error: Not found message
          schema:
            description: Not found
            properties:
              error:
                description: Not found message
                title: get_characters_character_id_calendar_event_id_404_not_found
                type: string
            title: get_characters_character_id_calendar_event_id_not_found
            type: object
        '420':
          description: Error limited
          examples:
            application/json:
              error: Error limited message
          schema:
            $ref: '#/definitions/error_limited'
        '500':
          description: Internal server error
          examples:
            application/json:
              error: Internal server error message
          schema:
            $ref: '#/definitions/internal_server_error'
        '503':
          description: Service unavailable
          examples:
            application/json:
              error: Service unavailable message
          schema:
            $ref: '#/definitions/service_unavailable'
        '504':
          description: Gateway timeout
          examples:
            application/json:
              error: Gateway timeout message
          schema:
            $ref: '#/definitions/gateway_timeout'
      security:
      - evesso:
        - esi-calendar.read_calendar_events.v1
      summary: Get an event
      tags:
      - Calendar
      x-alternate-versions:
      - latest
      - legacy
      - v3
      - v4
      x-cached-seconds: 5
    put:
      description: 'Set your response status to an event


        ---


        This route is cached for up to 5 seconds'
      operationId: put_characters_character_id_calendar_event_id
      parameters:
      - $ref: '#/parameters/character_id'
      - $ref: '#/parameters/datasource'
      - description: The ID of the event requested
        format: int32
        in: path
        name: event_id
        required: true
        type: integer
      - description: The response value to set, overriding current value
        in: body
        name: response
        required: true
        schema:
          description: response object
          properties:
            response:
              description: response string
              enum:
              - accepted
              - declined
              - tentative
              title: put_characters_character_id_calendar_event_id_response_response
              type: string
          required:
          - response
          title: put_characters_character_id_calendar_event_id_response
          type: object
      - $ref: '#/parameters/token'
      responses:
        '204':
          description: Event updated
        '400':
          description: Bad request
          examples:
            application/json:
              error: Bad request message
          schema:
            $ref: '#/definitions/bad_request'
        '401':
          description: Unauthorized
          examples:
            application/json:
              error: Unauthorized message
          schema:
            $ref: '#/definitions/unauthorized'
        '403':
          description: Forbidden
          examples:
            application/json:
              error: Forbidden message
          schema:
            $ref: '#/definitions/forbidden'
        '420':
          description: Error limited
          examples:
            application/json:
              error: Error limited message
          schema:
            $ref: '#/definitions/error_limited'
        '500':
          description: Internal server error
          examples:
            application/json:
              error: Internal server error message
          schema:
            $ref: '#/definitions/internal_server_error'
        '503':
          description: Service unavailable
          examples:
            application/json:
              error: Service unavailable message
          schema:
            $ref: '#/definitions/service_unavailable'
        '504':
          description: Gateway timeout
          examples:
            application/json:
              error: Gateway timeout message
          schema:
            $ref: '#/definitions/gateway_timeout'
      security:
      - evesso:
        - esi-calendar.respond_calendar_events.v1
      summary: Respond to an event
      tags:
      - Calendar
      x-alternate-versions:
      - latest
      - legacy
      - v3
      - v4
      x-cached-seconds: 5
components:
  schemas:
    internal_server_error:
      description: Internal server error model
      properties:
        error:
          description: Internal server error message
          type: string
          example: example
      required:
      - error
      title: Internal server error
      type: object
    forbidden:
      description: Forbidden model
      properties:
        error:
          description: Forbidden message
          type: string
          example: example
        sso_status:
          description: status code received from SSO
          type: integer
          example: 1
      required:
      - error
      title: Forbidden
      type: object
    service_unavailable:
      description: Service unavailable model
      properties:
        error:
          description: Service unavailable message
          type: string
          example: example
      required:
      - error
      title: Service unavailable
      type: object
    bad_request:
      description: Bad request model
      properties:
        error:
          description: Bad request message
          type: string
          example: example
      required:
      - error
      title: Bad request
      type: object
    unauthorized:
      description: Unauthorized model
      properties:
        error:
          description: Unauthorized message
          type: string
          example: example
      required:
      - error
      title: Unauthorized
      type: object
    gateway_timeout:
      description: Gateway timeout model
      properties:
        error:
          description: Gateway timeout message
          type: string
          example: example
        timeout:
          description: number of seconds the request was given
          type: integer
          example: 1
      required:
      - error
      title: Gateway timeout
      type: object
    error_limited:
      description: Error limited model
      properties:
        error:
          description: Error limited message
          type: string
          example: example
      required:
      - error
      title: Error limited
      type: object
  parameters:
    datasource:
      description: The server name you would like data from
      in: query
      name: datasource
      schema:
        type: string
        enum:
        - tranquility
        default: tranquility
    character_id:
      description: An EVE character ID
      in: path
      name: character_id
      required: true
      schema:
        type: integer
        format: int32
        minimum: 1
    token:
      description: Access token to use if unable to set a header
      in: query
      name: token
      schema:
        type: string
    If-None-Match:
      description: ETag from a previous request. A 304 will be returned if this matches the current ETag
      in: header
      name: If-None-Match
      schema:
        type: string
  securitySchemes:
    evesso:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.eveonline.com/v2/oauth/authorize
          scopes:
            esi-alliances.read_contacts.v1: EVE SSO scope esi-alliances.read_contacts.v1
            esi-assets.read_assets.v1: EVE SSO scope esi-assets.read_assets.v1
            esi-assets.read_corporation_assets.v1: EVE SSO scope esi-assets.read_corporation_assets.v1
            esi-calendar.read_calendar_events.v1: EVE SSO scope esi-calendar.read_calendar_events.v1
            esi-calendar.respond_calendar_events.v1: EVE SSO scope esi-calendar.respond_calendar_events.v1
            esi-characters.read_agents_research.v1: EVE SSO scope esi-characters.read_agents_research.v1
            esi-characters.read_blueprints.v1: EVE SSO scope esi-characters.read_blueprints.v1
            esi-characters.read_contacts.v1: EVE SSO scope esi-characters.read_contacts.v1
            esi-characters.read_corporation_roles.v1: EVE SSO scope esi-characters.read_corporation_roles.v1
            esi-characters.read_fatigue.v1: EVE SSO scope esi-characters.read_fatigue.v1
            esi-characters.read_fw_stats.v1: EVE SSO scope esi-characters.read_fw_stats.v1
            esi-characters.read_loyalty.v1: EVE SSO scope esi-characters.read_loyalty.v1
            esi-characters.read_medals.v1: EVE SSO scope esi-characters.read_medals.v1
            esi-characters.read_notifications.v1: EVE SSO scope esi-characters.read_notifications.v1
            esi-characters.read_standings.v1: EVE SSO scope esi-characters.read_standings.v1
            esi-characters.read_titles.v1: EVE SSO scope esi-characters.read_titles.v1
            esi-characters.write_contacts.v1: EVE SSO scope esi-characters.write_contacts.v1
            esi-clones.read_clones.v1: EVE SSO scope esi-clones.read_clones.v1
            esi-clones.read_implants.v1: EVE SSO scope esi-clones.read_implants.v1
            esi-contracts.read_character_contracts.v1: EVE SSO scope esi-contracts.read_character_contracts.v1
            esi-contracts.read_corporation_contracts.v1: EVE SSO scope esi-contracts.read_corporation_contracts.v1
            esi-corporations.read_blueprints.v1: EVE SSO scope esi-corporations.read_blueprints.v1
            esi-corporations.read_contacts.v1: EVE SSO scope esi-corporations.read_contacts.v1
            esi-corporations.read_container_logs.v1: EVE SSO scope esi-corporations.read_container_logs.v1
            esi-corporations.read_corporation_membership.v1: EVE SSO scope esi-corporations.read_corporation_membership.v1
            esi-corporations.read_divisions.v1: EVE SSO scope esi-corporations.read_divisions.v1
            esi-corporations.read_facilities.v1: EVE SSO scope esi-corporations.read_facilities.v1
            esi-corporations.read_fw_stats.v1: EVE SSO scope esi-corporations.read_fw_stats.v1
            esi-corporations.read_medals.v1: EVE SSO scope esi-corporations.read_medals.v1
            esi-corporations.read_standings.v1: EVE SSO scope esi-corporations.read_standings.v1
            esi-corporations.read_starbases.v1: EVE SSO scope esi-corporations.read_starbases.v1
            esi-corporations.read_structures.v1: EVE SSO scope esi-corporations.read_structures.v1
            esi-corporations.read_titles.v1: EVE SSO scope esi-corporations.read_titles.v1
            esi-corporations.track_members.v1: EVE SSO scope esi-corporations.track_members.v1
            esi-fittings.read_fittings.v1: EVE SSO scope esi-fittings.read_fittings.v1
            esi-fittings.write_fittings.v1: EVE SSO scope esi-fittings.write_fittings.v1
            esi-fleets.read_fleet.v1: EVE SSO scope esi-fleets.read_fleet.v1
            esi-fleets.write_fleet.v1: EVE SSO scope esi-fleets.write_fleet.v1
            esi-industry.read_character_jobs.v1: EVE SSO scope esi-industry.read_character_jobs.v1
            esi-industry.read_character_mining.v1: EVE SSO scope esi-industry.read_character_mining.v1
            esi-industry.read_corporation_jobs.v1: EVE SSO scope esi-industry.read_corporation_jobs.v1
            esi-industry.read_corporation_mining.v1: EVE SSO scope esi-industry.read_corporation_mining.v1
            esi-killmails.read_corporation_killmails.v1: EVE SSO scope esi-killmails.read_corporation_killmails.v1
            esi-killmails.read_killmails.v1: EVE SSO scope esi-killmails.read_killmails.v1
            esi-location.read_location.v1: EVE SSO scope esi-location.read_location.v1
            esi-location.read_online.v1: EVE SSO scope esi-location.read_online.v1
            esi-location.read_ship_type.v1: EVE SSO scope esi-location.read_ship_type.v1
            esi-mail.organize_mail.v1: EVE SSO scope esi-mail.organize_mail.v1
            esi-mail.read_mail.v1: EVE SSO scope esi-mail.read_mail.v1
            esi-mail.send_mail.v1: EVE SSO scope esi-mail.send_mail.v1
            esi-markets.read_character_orders.v1: EVE SSO scope esi-markets.read_character_orders.v1
            esi-markets.read_corporation_orders.v1: EVE SSO scope esi-markets.read_corporation_orders.v1
            esi-markets.structure_markets.v1: EVE SSO scope esi-markets.structure_markets.v1
            esi-planets.manage_planets.v1: EVE SSO scope esi-planets.manage_planets.v1
            esi-planets.read_customs_offices.v1: EVE SSO scope esi-planets.read_customs_offices.v1
            esi-search.search_structures.v1: EVE SSO scope esi-search.search_structures.v1
            esi-skills.read_skillqueue.v1: EVE SSO scope esi-skills.read_skillqueue.v1
            esi-skills.read_skills.v1: EVE SSO scope esi-skills.read_skills.v1
            esi-ui.open_window.v1: EVE SSO scope esi-ui.open_window.v1
            esi-ui.write_waypoint.v1: EVE SSO scope esi-ui.write_waypoint.v1
            esi-universe.read_structures.v1: EVE SSO scope esi-universe.read_structures.v1
            esi-wallet.read_character_wallet.v1: EVE SSO scope esi-wallet.read_character_wallet.v1
            esi-wallet.read_corporation_wallets.v1: EVE SSO scope esi-wallet.read_corporation_wallets.v1
definitions:
  internal_server_error:
    description: Internal server error model
    properties:
      error:
        description: Internal server error message
        type: string
    required:
    - error
    title: Internal server error
    type: object
  error_limited:
    description: Error limited model
    properties:
      error:
        description: Error limited message
        type: string
    required:
    - error
    title: Error limited
    type: object
  unauthorized:
    description: Unauthorized model
    properties:
      error:
        description: Unauthorized message
        type: string
    required:
    - error
    title: Unauthorized
    type: object
  service_unavailable:
    description: Service unavailable model
    properties:
      error:
        description: Service unavailable message
        type: string
    required:
    - error
    title: Service unavailable
    type: object
  forbidden:
    description: Forbidden model
    properties:
      error:
        description: Forbidden message
        type: string
      sso_status:
        description: status code received from SSO
        type: integer
    required:
    - error
    title: Forbidden
    type: object
  bad_request:
    description: Bad request model
    properties:
      error:
        description: Bad request message
        type: string
    required:
    - error
    title: Bad request
    type: object
  gateway_timeout:
    description: Gateway timeout model
    properties:
      error:
        description: Gateway timeout message
        type: string
      timeout:
        description: number of seconds the request was given
        type: integer
    required:
    - error
    title: Gateway timeout
    type: object
parameters:
  token:
    description: Access token to use if unable to set a header
    in: query
    name: token
    type: string
  If-None-Match:
    description: ETag from a previous request. A 304 will be returned if this matches the current ETag
    in: header
    name: If-None-Match
    type: string
  datasource:
    default: tranquility
    description: The server name you would like data from
    enum:
    - tranquility
    in: query
    name: datasource
    type: string
  character_id:
    description: An EVE character ID
    format: int32
    in: path
    minimum: 1
    name: character_id
    required: true
    type: integer
