openapi: 3.0.0
info:
  description: An OpenAPI for EVE Online
  title: EVE Swagger Interface Alliance Skills API
  version: '1.36'
servers:
- url: https://esi.evetech.net/latest
tags:
- name: Skills
paths:
  /characters/{character_id}/attributes/:
    get:
      description: 'Return attributes of a character


        ---

        Alternate route: `/dev/characters/{character_id}/attributes/`


        Alternate route: `/legacy/characters/{character_id}/attributes/`


        Alternate route: `/v1/characters/{character_id}/attributes/`


        ---

        This route is cached for up to 120 seconds'
      operationId: get_characters_character_id_attributes
      parameters:
      - $ref: '#/components/parameters/character_id'
      - $ref: '#/components/parameters/datasource'
      - $ref: '#/components/parameters/If-None-Match'
      - $ref: '#/components/parameters/token'
      responses:
        '200':
          description: Attributes of a character
          headers:
            Cache-Control:
              description: The caching mechanism used
              schema:
                type: string
            ETag:
              description: RFC7232 compliant entity tag
              schema:
                type: string
            Expires:
              description: RFC7231 formatted datetime string
              schema:
                type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              schema:
                type: string
          content:
            application/json:
              schema:
                description: 200 ok object
                properties:
                  accrued_remap_cooldown_date:
                    description: Neural remapping cooldown after a character uses remap accrued over time
                    format: date-time
                    title: get_characters_character_id_attributes_accrued_remap_cooldown_date
                    type: string
                  bonus_remaps:
                    description: Number of available bonus character neural remaps
                    format: int32
                    title: get_characters_character_id_attributes_bonus_remaps
                    type: integer
                  charisma:
                    description: charisma integer
                    format: int32
                    title: get_characters_character_id_attributes_charisma
                    type: integer
                  intelligence:
                    description: intelligence integer
                    format: int32
                    title: get_characters_character_id_attributes_intelligence
                    type: integer
                  last_remap_date:
                    description: Datetime of last neural remap, including usage of bonus remaps
                    format: date-time
                    title: get_characters_character_id_attributes_last_remap_date
                    type: string
                  memory:
                    description: memory integer
                    format: int32
                    title: get_characters_character_id_attributes_memory
                    type: integer
                  perception:
                    description: perception integer
                    format: int32
                    title: get_characters_character_id_attributes_perception
                    type: integer
                  willpower:
                    description: willpower integer
                    format: int32
                    title: get_characters_character_id_attributes_willpower
                    type: integer
                required:
                - charisma
                - intelligence
                - memory
                - perception
                - willpower
                title: get_characters_character_id_attributes_ok
                type: object
              examples:
                response:
                  value:
                    charisma: 20
                    intelligence: 20
                    memory: 20
                    perception: 20
                    willpower: 20
        '304':
          description: Not modified
          headers:
            Cache-Control:
              description: The caching mechanism used
              schema:
                type: string
            ETag:
              description: RFC7232 compliant entity tag
              schema:
                type: string
            Expires:
              description: RFC7231 formatted datetime string
              schema:
                type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              schema:
                type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request'
              examples:
                response:
                  value:
                    error: Bad request message
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
              examples:
                response:
                  value:
                    error: Unauthorized message
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
              examples:
                response:
                  value:
                    error: Forbidden message
        '420':
          description: Error limited
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_limited'
              examples:
                response:
                  value:
                    error: Error limited message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
              examples:
                response:
                  value:
                    error: Internal server error message
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_unavailable'
              examples:
                response:
                  value:
                    error: Service unavailable message
        '504':
          description: Gateway timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway_timeout'
              examples:
                response:
                  value:
                    error: Gateway timeout message
      security:
      - evesso:
        - esi-skills.read_skills.v1
      summary: EVE Online Get Character Attributes
      tags:
      - Skills
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 120
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /characters/{character_id}/skillqueue/:
    get:
      description: 'List the configured skill queue for the given character


        ---

        Alternate route: `/dev/characters/{character_id}/skillqueue/`


        Alternate route: `/legacy/characters/{character_id}/skillqueue/`


        Alternate route: `/v2/characters/{character_id}/skillqueue/`


        ---

        This route is cached for up to 120 seconds'
      operationId: get_characters_character_id_skillqueue
      parameters:
      - $ref: '#/components/parameters/character_id'
      - $ref: '#/components/parameters/datasource'
      - $ref: '#/components/parameters/If-None-Match'
      - $ref: '#/components/parameters/token'
      responses:
        '200':
          description: The current skill queue, sorted ascending by finishing time
          headers:
            Cache-Control:
              description: The caching mechanism used
              schema:
                type: string
            ETag:
              description: RFC7232 compliant entity tag
              schema:
                type: string
            Expires:
              description: RFC7231 formatted datetime string
              schema:
                type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              schema:
                type: string
          content:
            application/json:
              schema:
                description: 200 ok array
                items:
                  description: 200 ok object
                  properties:
                    finish_date:
                      description: Date on which training of the skill will complete. Omitted if the skill queue is paused.
                      format: date-time
                      title: get_characters_character_id_skillqueue_finish_date
                      type: string
                    finished_level:
                      description: finished_level integer
                      format: int32
                      maximum: 5
                      minimum: 0
                      title: get_characters_character_id_skillqueue_finished_level
                      type: integer
                    level_end_sp:
                      description: level_end_sp integer
                      format: int32
                      title: get_characters_character_id_skillqueue_level_end_sp
                      type: integer
                    level_start_sp:
                      description: Amount of SP that was in the skill when it started training it's current level. Used to calculate % of current level complete.
                      format: int32
                      title: get_characters_character_id_skillqueue_level_start_sp
                      type: integer
                    queue_position:
                      description: queue_position integer
                      format: int32
                      title: get_characters_character_id_skillqueue_queue_position
                      type: integer
                    skill_id:
                      description: skill_id integer
                      format: int32
                      title: get_characters_character_id_skillqueue_skill_id
                      type: integer
                    start_date:
                      description: start_date string
                      format: date-time
                      title: get_characters_character_id_skillqueue_start_date
                      type: string
                    training_start_sp:
                      description: training_start_sp integer
                      format: int32
                      title: get_characters_character_id_skillqueue_training_start_sp
                      type: integer
                  required:
                  - skill_id
                  - finished_level
                  - queue_position
                  title: get_characters_character_id_skillqueue_200_ok
                  type: object
                maxItems: 200
                title: get_characters_character_id_skillqueue_ok
                type: array
              examples:
                response:
                  value:
                  - finish_date: 2016-06-29 10:47:00+00:00
                    finished_level: 3
                    queue_position: 0
                    skill_id: 1
                    start_date: 2016-06-29 10:46:00+00:00
                  - finish_date: 2016-07-15 10:47:00+00:00
                    finished_level: 4
                    queue_position: 1
                    skill_id: 1
                    start_date: 2016-06-29 10:47:00+00:00
                  - finish_date: 2016-08-30 10:47:00+00:00
                    finished_level: 2
                    queue_position: 2
                    skill_id: 2
                    start_date: 2016-07-15 10:47:00+00:00
        '304':
          description: Not modified
          headers:
            Cache-Control:
              description: The caching mechanism used
              schema:
                type: string
            ETag:
              description: RFC7232 compliant entity tag
              schema:
                type: string
            Expires:
              description: RFC7231 formatted datetime string
              schema:
                type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              schema:
                type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request'
              examples:
                response:
                  value:
                    error: Bad request message
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
              examples:
                response:
                  value:
                    error: Unauthorized message
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
              examples:
                response:
                  value:
                    error: Forbidden message
        '420':
          description: Error limited
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_limited'
              examples:
                response:
                  value:
                    error: Error limited message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
              examples:
                response:
                  value:
                    error: Internal server error message
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_unavailable'
              examples:
                response:
                  value:
                    error: Service unavailable message
        '504':
          description: Gateway timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway_timeout'
              examples:
                response:
                  value:
                    error: Gateway timeout message
      security:
      - evesso:
        - esi-skills.read_skillqueue.v1
      summary: EVE Online Get Character's Skill Queue
      tags:
      - Skills
      x-alternate-versions:
      - dev
      - legacy
      - v2
      x-cached-seconds: 120
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /characters/{character_id}/skills/:
    get:
      description: 'List all trained skills for the given character


        ---

        Alternate route: `/dev/characters/{character_id}/skills/`


        Alternate route: `/v4/characters/{character_id}/skills/`


        ---

        This route is cached for up to 120 seconds'
      operationId: get_characters_character_id_skills
      parameters:
      - $ref: '#/components/parameters/character_id'
      - $ref: '#/components/parameters/datasource'
      - $ref: '#/components/parameters/If-None-Match'
      - $ref: '#/components/parameters/token'
      responses:
        '200':
          description: Known skills for the character
          headers:
            Cache-Control:
              description: The caching mechanism used
              schema:
                type: string
            ETag:
              description: RFC7232 compliant entity tag
              schema:
                type: string
            Expires:
              description: RFC7231 formatted datetime string
              schema:
                type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              schema:
                type: string
          content:
            application/json:
              schema:
                description: 200 ok object
                properties:
                  skills:
                    description: skills array
                    items:
                      description: skill object
                      properties:
                        active_skill_level:
                          description: active_skill_level integer
                          format: int32
                          title: get_characters_character_id_skills_active_skill_level
                          type: integer
                        skill_id:
                          description: skill_id integer
                          format: int32
                          title: get_characters_character_id_skills_skill_id
                          type: integer
                        skillpoints_in_skill:
                          description: skillpoints_in_skill integer
                          format: int64
                          title: get_characters_character_id_skills_skillpoints_in_skill
                          type: integer
                        trained_skill_level:
                          description: trained_skill_level integer
                          format: int32
                          title: get_characters_character_id_skills_trained_skill_level
                          type: integer
                      required:
                      - skill_id
                      - skillpoints_in_skill
                      - trained_skill_level
                      - active_skill_level
                      title: get_characters_character_id_skills_skill
                      type: object
                    maxItems: 1000
                    title: get_characters_character_id_skills_skills
                    type: array
                  total_sp:
                    description: total_sp integer
                    format: int64
                    title: get_characters_character_id_skills_total_sp
                    type: integer
                  unallocated_sp:
                    description: Skill points available to be assigned
                    format: int32
                    title: get_characters_character_id_skills_unallocated_sp
                    type: integer
                required:
                - skills
                - total_sp
                title: get_characters_character_id_skills_ok
                type: object
              examples:
                response:
                  value:
                    skills:
                    - active_skill_level: 3
                      skill_id: 1
                      skillpoints_in_skill: 10000
                      trained_skill_level: 4
                    - active_skill_level: 1
                      skill_id: 2
                      skillpoints_in_skill: 10000
                      trained_skill_level: 1
                    total_sp: 20000
        '304':
          description: Not modified
          headers:
            Cache-Control:
              description: The caching mechanism used
              schema:
                type: string
            ETag:
              description: RFC7232 compliant entity tag
              schema:
                type: string
            Expires:
              description: RFC7231 formatted datetime string
              schema:
                type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              schema:
                type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request'
              examples:
                response:
                  value:
                    error: Bad request message
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
              examples:
                response:
                  value:
                    error: Unauthorized message
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
              examples:
                response:
                  value:
                    error: Forbidden message
        '420':
          description: Error limited
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_limited'
              examples:
                response:
                  value:
                    error: Error limited message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
              examples:
                response:
                  value:
                    error: Internal server error message
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_unavailable'
              examples:
                response:
                  value:
                    error: Service unavailable message
        '504':
          description: Gateway timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway_timeout'
              examples:
                response:
                  value:
                    error: Gateway timeout message
      security:
      - evesso:
        - esi-skills.read_skills.v1
      summary: EVE Online Get Character Skills
      tags:
      - Skills
      x-alternate-versions:
      - dev
      - v4
      x-cached-seconds: 120
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /v1/characters/{character_id}/attributes/:
    get:
      description: 'Return attributes of a character


        ---


        This route is cached for up to 120 seconds'
      operationId: get_characters_character_id_attributes
      parameters:
      - $ref: '#/parameters/character_id'
      - $ref: '#/parameters/datasource'
      - $ref: '#/parameters/If-None-Match'
      - $ref: '#/parameters/token'
      responses:
        '200':
          description: Attributes of a character
          examples:
            application/json:
              charisma: 20
              intelligence: 20
              memory: 20
              perception: 20
              willpower: 20
          headers:
            Cache-Control:
              description: The caching mechanism used
              type: string
            ETag:
              description: RFC7232 compliant entity tag
              type: string
            Expires:
              description: RFC7231 formatted datetime string
              type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              type: string
          schema:
            description: 200 ok object
            properties:
              accrued_remap_cooldown_date:
                description: Neural remapping cooldown after a character uses remap accrued over time
                format: date-time
                title: get_characters_character_id_attributes_accrued_remap_cooldown_date
                type: string
              bonus_remaps:
                description: Number of available bonus character neural remaps
                format: int32
                title: get_characters_character_id_attributes_bonus_remaps
                type: integer
              charisma:
                description: charisma integer
                format: int32
                title: get_characters_character_id_attributes_charisma
                type: integer
              intelligence:
                description: intelligence integer
                format: int32
                title: get_characters_character_id_attributes_intelligence
                type: integer
              last_remap_date:
                description: Datetime of last neural remap, including usage of bonus remaps
                format: date-time
                title: get_characters_character_id_attributes_last_remap_date
                type: string
              memory:
                description: memory integer
                format: int32
                title: get_characters_character_id_attributes_memory
                type: integer
              perception:
                description: perception integer
                format: int32
                title: get_characters_character_id_attributes_perception
                type: integer
              willpower:
                description: willpower integer
                format: int32
                title: get_characters_character_id_attributes_willpower
                type: integer
            required:
            - charisma
            - intelligence
            - memory
            - perception
            - willpower
            title: get_characters_character_id_attributes_ok
            type: object
        '304':
          description: Not modified
          headers:
            Cache-Control:
              description: The caching mechanism used
              type: string
            ETag:
              description: RFC7232 compliant entity tag
              type: string
            Expires:
              description: RFC7231 formatted datetime string
              type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              type: string
        '400':
          description: Bad request
          examples:
            application/json:
              error: Bad request message
          schema:
            $ref: '#/definitions/bad_request'
        '401':
          description: Unauthorized
          examples:
            application/json:
              error: Unauthorized message
          schema:
            $ref: '#/definitions/unauthorized'
        '403':
          description: Forbidden
          examples:
            application/json:
              error: Forbidden message
          schema:
            $ref: '#/definitions/forbidden'
        '420':
          description: Error limited
          examples:
            application/json:
              error: Error limited message
          schema:
            $ref: '#/definitions/error_limited'
        '500':
          description: Internal server error
          examples:
            application/json:
              error: Internal server error message
          schema:
            $ref: '#/definitions/internal_server_error'
        '503':
          description: Service unavailable
          examples:
            application/json:
              error: Service unavailable message
          schema:
            $ref: '#/definitions/service_unavailable'
        '504':
          description: Gateway timeout
          examples:
            application/json:
              error: Gateway timeout message
          schema:
            $ref: '#/definitions/gateway_timeout'
      security:
      - evesso:
        - esi-skills.read_skills.v1
      summary: Get character attributes
      tags:
      - Skills
      x-alternate-versions:
      - latest
      - legacy
      - v1
      x-cached-seconds: 120
  /v2/characters/{character_id}/skillqueue/:
    get:
      description: 'List the configured skill queue for the given character


        ---


        This route is cached for up to 120 seconds'
      operationId: get_characters_character_id_skillqueue
      parameters:
      - $ref: '#/parameters/character_id'
      - $ref: '#/parameters/datasource'
      - $ref: '#/parameters/If-None-Match'
      - $ref: '#/parameters/token'
      responses:
        '200':
          description: The current skill queue, sorted ascending by finishing time
          examples:
            application/json:
            - finish_date: '2016-06-29T10:47:00Z'
              finished_level: 3
              queue_position: 0
              skill_id: 1
              start_date: '2016-06-29T10:46:00Z'
            - finish_date: '2016-07-15T10:47:00Z'
              finished_level: 4
              queue_position: 1
              skill_id: 1
              start_date: '2016-06-29T10:47:00Z'
            - finish_date: '2016-08-30T10:47:00Z'
              finished_level: 2
              queue_position: 2
              skill_id: 2
              start_date: '2016-07-15T10:47:00Z'
          headers:
            Cache-Control:
              description: The caching mechanism used
              type: string
            ETag:
              description: RFC7232 compliant entity tag
              type: string
            Expires:
              description: RFC7231 formatted datetime string
              type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              type: string
          schema:
            description: 200 ok array
            items:
              description: 200 ok object
              properties:
                finish_date:
                  description: Date on which training of the skill will complete. Omitted if the skill queue is paused.
                  format: date-time
                  title: get_characters_character_id_skillqueue_finish_date
                  type: string
                finished_level:
                  description: finished_level integer
                  format: int32
                  maximum: 5
                  minimum: 0
                  title: get_characters_character_id_skillqueue_finished_level
                  type: integer
                level_end_sp:
                  description: level_end_sp integer
                  format: int32
                  title: get_characters_character_id_skillqueue_level_end_sp
                  type: integer
                level_start_sp:
                  description: Amount of SP that was in the skill when it started training it's current level. Used to calculate % of current level complete.
                  format: int32
                  title: get_characters_character_id_skillqueue_level_start_sp
                  type: integer
                queue_position:
                  description: queue_position integer
                  format: int32
                  title: get_characters_character_id_skillqueue_queue_position
                  type: integer
                skill_id:
                  description: skill_id integer
                  format: int32
                  title: get_characters_character_id_skillqueue_skill_id
                  type: integer
                start_date:
                  description: start_date string
                  format: date-time
                  title: get_characters_character_id_skillqueue_start_date
                  type: string
                training_start_sp:
                  description: training_start_sp integer
                  format: int32
                  title: get_characters_character_id_skillqueue_training_start_sp
                  type: integer
              required:
              - skill_id
              - finished_level
              - queue_position
              title: get_characters_character_id_skillqueue_200_ok
              type: object
            maxItems: 200
            title: get_characters_character_id_skillqueue_ok
            type: array
        '304':
          description: Not modified
          headers:
            Cache-Control:
              description: The caching mechanism used
              type: string
            ETag:
              description: RFC7232 compliant entity tag
              type: string
            Expires:
              description: RFC7231 formatted datetime string
              type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              type: string
        '400':
          description: Bad request
          examples:
            application/json:
              error: Bad request message
          schema:
            $ref: '#/definitions/bad_request'
        '401':
          description: Unauthorized
          examples:
            application/json:
              error: Unauthorized message
          schema:
            $ref: '#/definitions/unauthorized'
        '403':
          description: Forbidden
          examples:
            application/json:
              error: Forbidden message
          schema:
            $ref: '#/definitions/forbidden'
        '420':
          description: Error limited
          examples:
            application/json:
              error: Error limited message
          schema:
            $ref: '#/definitions/error_limited'
        '500':
          description: Internal server error
          examples:
            application/json:
              error: Internal server error message
          schema:
            $ref: '#/definitions/internal_server_error'
        '503':
          description: Service unavailable
          examples:
            application/json:
              error: Service unavailable message
          schema:
            $ref: '#/definitions/service_unavailable'
        '504':
          description: Gateway timeout
          examples:
            application/json:
              error: Gateway timeout message
          schema:
            $ref: '#/definitions/gateway_timeout'
      security:
      - evesso:
        - esi-skills.read_skillqueue.v1
      summary: Get character's skill queue
      tags:
      - Skills
      x-alternate-versions:
      - latest
      - legacy
      - v2
      x-cached-seconds: 120
  /v4/characters/{character_id}/skills/:
    get:
      description: 'List all trained skills for the given character


        ---


        This route is cached for up to 120 seconds'
      operationId: get_characters_character_id_skills
      parameters:
      - $ref: '#/parameters/character_id'
      - $ref: '#/parameters/datasource'
      - $ref: '#/parameters/If-None-Match'
      - $ref: '#/parameters/token'
      responses:
        '200':
          description: Known skills for the character
          examples:
            application/json:
              skills:
              - active_skill_level: 3
                skill_id: 1
                skillpoints_in_skill: 10000
                trained_skill_level: 4
              - active_skill_level: 1
                skill_id: 2
                skillpoints_in_skill: 10000
                trained_skill_level: 1
              total_sp: 20000
          headers:
            Cache-Control:
              description: The caching mechanism used
              type: string
            ETag:
              description: RFC7232 compliant entity tag
              type: string
            Expires:
              description: RFC7231 formatted datetime string
              type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              type: string
          schema:
            description: 200 ok object
            properties:
              skills:
                description: skills array
                items:
                  description: skill object
                  properties:
                    active_skill_level:
                      description: active_skill_level integer
                      format: int32
                      title: get_characters_character_id_skills_active_skill_level
                      type: integer
                    skill_id:
                      description: skill_id integer
                      format: int32
                      title: get_characters_character_id_skills_skill_id
                      type: integer
                    skillpoints_in_skill:
                      description: skillpoints_in_skill integer
                      format: int64
                      title: get_characters_character_id_skills_skillpoints_in_skill
                      type: integer
                    trained_skill_level:
                      description: trained_skill_level integer
                      format: int32
                      title: get_characters_character_id_skills_trained_skill_level
                      type: integer
                  required:
                  - skill_id
                  - skillpoints_in_skill
                  - trained_skill_level
                  - active_skill_level
                  title: get_characters_character_id_skills_skill
                  type: object
                maxItems: 1000
                title: get_characters_character_id_skills_skills
                type: array
              total_sp:
                description: total_sp integer
                format: int64
                title: get_characters_character_id_skills_total_sp
                type: integer
              unallocated_sp:
                description: Skill points available to be assigned
                format: int32
                title: get_characters_character_id_skills_unallocated_sp
                type: integer
            required:
            - skills
            - total_sp
            title: get_characters_character_id_skills_ok
            type: object
        '304':
          description: Not modified
          headers:
            Cache-Control:
              description: The caching mechanism used
              type: string
            ETag:
              description: RFC7232 compliant entity tag
              type: string
            Expires:
              description: RFC7231 formatted datetime string
              type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              type: string
        '400':
          description: Bad request
          examples:
            application/json:
              error: Bad request message
          schema:
            $ref: '#/definitions/bad_request'
        '401':
          description: Unauthorized
          examples:
            application/json:
              error: Unauthorized message
          schema:
            $ref: '#/definitions/unauthorized'
        '403':
          description: Forbidden
          examples:
            application/json:
              error: Forbidden message
          schema:
            $ref: '#/definitions/forbidden'
        '420':
          description: Error limited
          examples:
            application/json:
              error: Error limited message
          schema:
            $ref: '#/definitions/error_limited'
        '500':
          description: Internal server error
          examples:
            application/json:
              error: Internal server error message
          schema:
            $ref: '#/definitions/internal_server_error'
        '503':
          description: Service unavailable
          examples:
            application/json:
              error: Service unavailable message
          schema:
            $ref: '#/definitions/service_unavailable'
        '504':
          description: Gateway timeout
          examples:
            application/json:
              error: Gateway timeout message
          schema:
            $ref: '#/definitions/gateway_timeout'
      security:
      - evesso:
        - esi-skills.read_skills.v1
      summary: Get character skills
      tags:
      - Skills
      x-alternate-versions:
      - latest
      - v4
      x-cached-seconds: 120
components:
  schemas:
    internal_server_error:
      description: Internal server error model
      properties:
        error:
          description: Internal server error message
          type: string
          example: example
      required:
      - error
      title: Internal server error
      type: object
    forbidden:
      description: Forbidden model
      properties:
        error:
          description: Forbidden message
          type: string
          example: example
        sso_status:
          description: status code received from SSO
          type: integer
          example: 1
      required:
      - error
      title: Forbidden
      type: object
    service_unavailable:
      description: Service unavailable model
      properties:
        error:
          description: Service unavailable message
          type: string
          example: example
      required:
      - error
      title: Service unavailable
      type: object
    bad_request:
      description: Bad request model
      properties:
        error:
          description: Bad request message
          type: string
          example: example
      required:
      - error
      title: Bad request
      type: object
    unauthorized:
      description: Unauthorized model
      properties:
        error:
          description: Unauthorized message
          type: string
          example: example
      required:
      - error
      title: Unauthorized
      type: object
    gateway_timeout:
      description: Gateway timeout model
      properties:
        error:
          description: Gateway timeout message
          type: string
          example: example
        timeout:
          description: number of seconds the request was given
          type: integer
          example: 1
      required:
      - error
      title: Gateway timeout
      type: object
    error_limited:
      description: Error limited model
      properties:
        error:
          description: Error limited message
          type: string
          example: example
      required:
      - error
      title: Error limited
      type: object
  parameters:
    datasource:
      description: The server name you would like data from
      in: query
      name: datasource
      schema:
        type: string
        enum:
        - tranquility
        default: tranquility
    character_id:
      description: An EVE character ID
      in: path
      name: character_id
      required: true
      schema:
        type: integer
        format: int32
        minimum: 1
    token:
      description: Access token to use if unable to set a header
      in: query
      name: token
      schema:
        type: string
    If-None-Match:
      description: ETag from a previous request. A 304 will be returned if this matches the current ETag
      in: header
      name: If-None-Match
      schema:
        type: string
  securitySchemes:
    evesso:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.eveonline.com/v2/oauth/authorize
          scopes:
            esi-alliances.read_contacts.v1: EVE SSO scope esi-alliances.read_contacts.v1
            esi-assets.read_assets.v1: EVE SSO scope esi-assets.read_assets.v1
            esi-assets.read_corporation_assets.v1: EVE SSO scope esi-assets.read_corporation_assets.v1
            esi-calendar.read_calendar_events.v1: EVE SSO scope esi-calendar.read_calendar_events.v1
            esi-calendar.respond_calendar_events.v1: EVE SSO scope esi-calendar.respond_calendar_events.v1
            esi-characters.read_agents_research.v1: EVE SSO scope esi-characters.read_agents_research.v1
            esi-characters.read_blueprints.v1: EVE SSO scope esi-characters.read_blueprints.v1
            esi-characters.read_contacts.v1: EVE SSO scope esi-characters.read_contacts.v1
            esi-characters.read_corporation_roles.v1: EVE SSO scope esi-characters.read_corporation_roles.v1
            esi-characters.read_fatigue.v1: EVE SSO scope esi-characters.read_fatigue.v1
            esi-characters.read_fw_stats.v1: EVE SSO scope esi-characters.read_fw_stats.v1
            esi-characters.read_loyalty.v1: EVE SSO scope esi-characters.read_loyalty.v1
            esi-characters.read_medals.v1: EVE SSO scope esi-characters.read_medals.v1
            esi-characters.read_notifications.v1: EVE SSO scope esi-characters.read_notifications.v1
            esi-characters.read_standings.v1: EVE SSO scope esi-characters.read_standings.v1
            esi-characters.read_titles.v1: EVE SSO scope esi-characters.read_titles.v1
            esi-characters.write_contacts.v1: EVE SSO scope esi-characters.write_contacts.v1
            esi-clones.read_clones.v1: EVE SSO scope esi-clones.read_clones.v1
            esi-clones.read_implants.v1: EVE SSO scope esi-clones.read_implants.v1
            esi-contracts.read_character_contracts.v1: EVE SSO scope esi-contracts.read_character_contracts.v1
            esi-contracts.read_corporation_contracts.v1: EVE SSO scope esi-contracts.read_corporation_contracts.v1
            esi-corporations.read_blueprints.v1: EVE SSO scope esi-corporations.read_blueprints.v1
            esi-corporations.read_contacts.v1: EVE SSO scope esi-corporations.read_contacts.v1
            esi-corporations.read_container_logs.v1: EVE SSO scope esi-corporations.read_container_logs.v1
            esi-corporations.read_corporation_membership.v1: EVE SSO scope esi-corporations.read_corporation_membership.v1
            esi-corporations.read_divisions.v1: EVE SSO scope esi-corporations.read_divisions.v1
            esi-corporations.read_facilities.v1: EVE SSO scope esi-corporations.read_facilities.v1
            esi-corporations.read_fw_stats.v1: EVE SSO scope esi-corporations.read_fw_stats.v1
            esi-corporations.read_medals.v1: EVE SSO scope esi-corporations.read_medals.v1
            esi-corporations.read_standings.v1: EVE SSO scope esi-corporations.read_standings.v1
            esi-corporations.read_starbases.v1: EVE SSO scope esi-corporations.read_starbases.v1
            esi-corporations.read_structures.v1: EVE SSO scope esi-corporations.read_structures.v1
            esi-corporations.read_titles.v1: EVE SSO scope esi-corporations.read_titles.v1
            esi-corporations.track_members.v1: EVE SSO scope esi-corporations.track_members.v1
            esi-fittings.read_fittings.v1: EVE SSO scope esi-fittings.read_fittings.v1
            esi-fittings.write_fittings.v1: EVE SSO scope esi-fittings.write_fittings.v1
            esi-fleets.read_fleet.v1: EVE SSO scope esi-fleets.read_fleet.v1
            esi-fleets.write_fleet.v1: EVE SSO scope esi-fleets.write_fleet.v1
            esi-industry.read_character_jobs.v1: EVE SSO scope esi-industry.read_character_jobs.v1
            esi-industry.read_character_mining.v1: EVE SSO scope esi-industry.read_character_mining.v1
            esi-industry.read_corporation_jobs.v1: EVE SSO scope esi-industry.read_corporation_jobs.v1
            esi-industry.read_corporation_mining.v1: EVE SSO scope esi-industry.read_corporation_mining.v1
            esi-killmails.read_corporation_killmails.v1: EVE SSO scope esi-killmails.read_corporation_killmails.v1
            esi-killmails.read_killmails.v1: EVE SSO scope esi-killmails.read_killmails.v1
            esi-location.read_location.v1: EVE SSO scope esi-location.read_location.v1
            esi-location.read_online.v1: EVE SSO scope esi-location.read_online.v1
            esi-location.read_ship_type.v1: EVE SSO scope esi-location.read_ship_type.v1
            esi-mail.organize_mail.v1: EVE SSO scope esi-mail.organize_mail.v1
            esi-mail.read_mail.v1: EVE SSO scope esi-mail.read_mail.v1
            esi-mail.send_mail.v1: EVE SSO scope esi-mail.send_mail.v1
            esi-markets.read_character_orders.v1: EVE SSO scope esi-markets.read_character_orders.v1
            esi-markets.read_corporation_orders.v1: EVE SSO scope esi-markets.read_corporation_orders.v1
            esi-markets.structure_markets.v1: EVE SSO scope esi-markets.structure_markets.v1
            esi-planets.manage_planets.v1: EVE SSO scope esi-planets.manage_planets.v1
            esi-planets.read_customs_offices.v1: EVE SSO scope esi-planets.read_customs_offices.v1
            esi-search.search_structures.v1: EVE SSO scope esi-search.search_structures.v1
            esi-skills.read_skillqueue.v1: EVE SSO scope esi-skills.read_skillqueue.v1
            esi-skills.read_skills.v1: EVE SSO scope esi-skills.read_skills.v1
            esi-ui.open_window.v1: EVE SSO scope esi-ui.open_window.v1
            esi-ui.write_waypoint.v1: EVE SSO scope esi-ui.write_waypoint.v1
            esi-universe.read_structures.v1: EVE SSO scope esi-universe.read_structures.v1
            esi-wallet.read_character_wallet.v1: EVE SSO scope esi-wallet.read_character_wallet.v1
            esi-wallet.read_corporation_wallets.v1: EVE SSO scope esi-wallet.read_corporation_wallets.v1
definitions:
  internal_server_error:
    description: Internal server error model
    properties:
      error:
        description: Internal server error message
        type: string
    required:
    - error
    title: Internal server error
    type: object
  error_limited:
    description: Error limited model
    properties:
      error:
        description: Error limited message
        type: string
    required:
    - error
    title: Error limited
    type: object
  unauthorized:
    description: Unauthorized model
    properties:
      error:
        description: Unauthorized message
        type: string
    required:
    - error
    title: Unauthorized
    type: object
  service_unavailable:
    description: Service unavailable model
    properties:
      error:
        description: Service unavailable message
        type: string
    required:
    - error
    title: Service unavailable
    type: object
  forbidden:
    description: Forbidden model
    properties:
      error:
        description: Forbidden message
        type: string
      sso_status:
        description: status code received from SSO
        type: integer
    required:
    - error
    title: Forbidden
    type: object
  bad_request:
    description: Bad request model
    properties:
      error:
        description: Bad request message
        type: string
    required:
    - error
    title: Bad request
    type: object
  gateway_timeout:
    description: Gateway timeout model
    properties:
      error:
        description: Gateway timeout message
        type: string
      timeout:
        description: number of seconds the request was given
        type: integer
    required:
    - error
    title: Gateway timeout
    type: object
parameters:
  token:
    description: Access token to use if unable to set a header
    in: query
    name: token
    type: string
  If-None-Match:
    description: ETag from a previous request. A 304 will be returned if this matches the current ETag
    in: header
    name: If-None-Match
    type: string
  datasource:
    default: tranquility
    description: The server name you would like data from
    enum:
    - tranquility
    in: query
    name: datasource
    type: string
  character_id:
    description: An EVE character ID
    format: int32
    in: path
    minimum: 1
    name: character_id
    required: true
    type: integer
